### ISSUE TITLE
Double click on gradle run raises exception

### ISSUE THREAD

**Issue by kharf** [korlibs/korge-intellij-plugin#30]
open gradle window -> tasks -> run -> runJvm raises:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'module' of org/jetbrains/plugins/gradle/execution/GradleRunnerUtil.resolveProjectPath must not be null
	at org.jetbrains.plugins.gradle.execution.GradleRunnerUtil.$$$reportNull$$$0(GradleRunnerUtil.java)
	at org.jetbrains.plugins.gradle.execution.GradleRunnerUtil.resolveProjectPath(GradleRunnerUtil.java)
	at com.soywiz.korge.intellij.execution.KorgeRunConfigurationProducer.getProjectPath(KorgeRunConfigurationProducer.kt:54)
	at com.soywiz.korge.intellij.execution.KorgeRunConfigurationProducer.isConfigurationFromContext(KorgeRunConfigurationProducer.kt:41)
	at com.soywiz.korge.intellij.execution.KorgeRunConfigurationProducer.isConfigurationFromContext(KorgeRunConfigurationProducer.kt:28)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:234)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:253)
	at com.intellij.openapi.externalSystem.action.task.RunExternalSystemTaskAction.findOrGet(RunExternalSystemTaskAction.java:69)
	at com.intellij.openapi.externalSystem.action.task.RunExternalSystemTaskAction.perform(RunExternalSystemTaskAction.java:57)
	at com.intellij.openapi.externalSystem.action.task.RunExternalSystemTaskAction.perform(RunExternalSystemTaskAction.java:41)
	at com.intellij.openapi.externalSystem.action.ExternalSystemNodeAction.actionPerformed(ExternalSystemNodeAction.java:53)
	at com.intellij.openapi.externalSystem.action.ExternalSystemActionUtil.executeAction(ExternalSystemActionUtil.java:44)
	at com.intellij.openapi.externalSystem.view.ExternalProjectsViewImpl.handleDoubleClickOrEnter(ExternalProjectsViewImpl.java:267)
	at com.intellij.openapi.externalSystem.view.ExternalSystemNode.handleDoubleClickOrEnter(ExternalSystemNode.java:411)
	at com.intellij.ui.treeStructure.SimpleTree.lambda$handleDoubleClickOrEnter$1(SimpleTree.java:390)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Only right clicking works

**Comment by soywiz** [comment]
Woops :) Thanks for reporting

**Comment by kharf** [comment]
sure :) - one note: this also occurs for all my other non korge projects

**Comment by soywiz** [comment]
Fixed already. Will be available on the next update

**Comment by ncgerharra** [comment]
Cool! Will the plugin be updated soon, or is there a workaround for now?

**Comment by soywiz** [comment]
There are a few bugs in the IntelliJ plugin that started happening recently, I have to check it carefully and make a new version. I plan to release KorGE 2.1.0 this week, and I will work on the plugin after that. So you could expect it to be fixed sometime next week or in a couple of weeks depending on the time it takes to be accepted.

**Comment by ncgerharra** [comment]
Highly anticipated ;o)
